// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: api/user/user.proto

package user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendSms       string                 `protobuf:"bytes,2,opt,name=sendSms,proto3" json:"sendSms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRegister) Reset() {
	*x = UserLoginRegister{}
	mi := &file_api_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRegister) ProtoMessage() {}

func (x *UserLoginRegister) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRegister.ProtoReflect.Descriptor instead.
func (*UserLoginRegister) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginRegister) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserLoginRegister) GetSendSms() string {
	if x != nil {
		return x.SendSms
	}
	return ""
}

// PleaseReturn 参数返回三要素
type PleaseReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleaseReturn) Reset() {
	*x = PleaseReturn{}
	mi := &file_api_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleaseReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleaseReturn) ProtoMessage() {}

func (x *PleaseReturn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleaseReturn.ProtoReflect.Descriptor instead.
func (*PleaseReturn) Descriptor() ([]byte, []int) {
	return file_api_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *PleaseReturn) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PleaseReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PleaseReturn) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_user_user_proto protoreflect.FileDescriptor

const file_api_user_user_proto_rawDesc = "" +
	"\n" +
	"\x13api/user/user.proto\x12\bapi.user\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"E\n" +
	"\x11UserLoginRegister\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x18\n" +
	"\asendSms\x18\x02 \x01(\tR\asendSms\"a\n" +
	"\fPleaseReturn\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data2{\n" +
	"\x04User\x12s\n" +
	"\x18PassengerUserMobileLogin\x12\x1b.api.user.UserLoginRegister\x1a\x16.api.user.PleaseReturn\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/passenger/mobile/loginB'\n" +
	"\bapi.userP\x01Z\x19kratosItems/api/user;userb\x06proto3"

var (
	file_api_user_user_proto_rawDescOnce sync.Once
	file_api_user_user_proto_rawDescData []byte
)

func file_api_user_user_proto_rawDescGZIP() []byte {
	file_api_user_user_proto_rawDescOnce.Do(func() {
		file_api_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_user_proto_rawDesc), len(file_api_user_user_proto_rawDesc)))
	})
	return file_api_user_user_proto_rawDescData
}

var file_api_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_user_user_proto_goTypes = []any{
	(*UserLoginRegister)(nil), // 0: api.user.UserLoginRegister
	(*PleaseReturn)(nil),      // 1: api.user.PleaseReturn
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_api_user_user_proto_depIdxs = []int32{
	2, // 0: api.user.PleaseReturn.data:type_name -> google.protobuf.Struct
	0, // 1: api.user.User.PassengerUserMobileLogin:input_type -> api.user.UserLoginRegister
	1, // 2: api.user.User.PassengerUserMobileLogin:output_type -> api.user.PleaseReturn
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_user_user_proto_init() }
func file_api_user_user_proto_init() {
	if File_api_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_user_proto_rawDesc), len(file_api_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_user_proto_goTypes,
		DependencyIndexes: file_api_user_user_proto_depIdxs,
		MessageInfos:      file_api_user_user_proto_msgTypes,
	}.Build()
	File_api_user_user_proto = out.File
	file_api_user_user_proto_goTypes = nil
	file_api_user_user_proto_depIdxs = nil
}
