// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.11
// source: api/user/user.proto

package user

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserPassengerUserMobileLogin = "/api.user.User/PassengerUserMobileLogin"

type UserHTTPServer interface {
	// PassengerUserMobileLogin 用户手机验证码登录 POST请求
	PassengerUserMobileLogin(context.Context, *UserLoginRegister) (*PleaseReturn, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.POST("/passenger/mobile/login", _User_PassengerUserMobileLogin0_HTTP_Handler(srv))
}

func _User_PassengerUserMobileLogin0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserLoginRegister
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserPassengerUserMobileLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PassengerUserMobileLogin(ctx, req.(*UserLoginRegister))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	// PassengerUserMobileLogin 用户手机验证码登录 POST请求
	PassengerUserMobileLogin(ctx context.Context, req *UserLoginRegister, opts ...http.CallOption) (rsp *PleaseReturn, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

// PassengerUserMobileLogin 用户手机验证码登录 POST请求
func (c *UserHTTPClientImpl) PassengerUserMobileLogin(ctx context.Context, in *UserLoginRegister, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/passenger/mobile/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserPassengerUserMobileLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
