// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: api/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_PassengerUserMobileLogin_FullMethodName    = "/api.user.User/PassengerUserMobileLogin"
	User_PassengerUserMobileRegister_FullMethodName = "/api.user.User/PassengerUserMobileRegister"
	User_PassengerUserPasswordLogin_FullMethodName  = "/api.user.User/PassengerUserPasswordLogin"
	User_GetUserInfo_FullMethodName                 = "/api.user.User/GetUserInfo"
	User_UpdateUserInfo_FullMethodName              = "/api.user.User/UpdateUserInfo"
	User_SendVerifyCode_FullMethodName              = "/api.user.User/SendVerifyCode"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// 用户手机验证码登录 POST请求
	PassengerUserMobileLogin(ctx context.Context, in *UserLoginRegister, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 用户手机验证码注册 POST请求
	PassengerUserMobileRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 用户密码登录 POST请求
	PassengerUserPasswordLogin(ctx context.Context, in *UserPasswordLoginRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 获取用户信息 GET请求
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 更新用户信息 PUT请求
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 发送验证码 POST请求
	SendVerifyCode(ctx context.Context, in *SendVerifyCodeRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) PassengerUserMobileLogin(ctx context.Context, in *UserLoginRegister, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_PassengerUserMobileLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) PassengerUserMobileRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_PassengerUserMobileRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) PassengerUserPasswordLogin(ctx context.Context, in *UserPasswordLoginRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_PassengerUserPasswordLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_UpdateUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SendVerifyCode(ctx context.Context, in *SendVerifyCodeRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, User_SendVerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	// 用户手机验证码登录 POST请求
	PassengerUserMobileLogin(context.Context, *UserLoginRegister) (*PleaseReturn, error)
	// 用户手机验证码注册 POST请求
	PassengerUserMobileRegister(context.Context, *UserRegisterRequest) (*PleaseReturn, error)
	// 用户密码登录 POST请求
	PassengerUserPasswordLogin(context.Context, *UserPasswordLoginRequest) (*PleaseReturn, error)
	// 获取用户信息 GET请求
	GetUserInfo(context.Context, *GetUserInfoRequest) (*PleaseReturn, error)
	// 更新用户信息 PUT请求
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*PleaseReturn, error)
	// 发送验证码 POST请求
	SendVerifyCode(context.Context, *SendVerifyCodeRequest) (*PleaseReturn, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) PassengerUserMobileLogin(context.Context, *UserLoginRegister) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassengerUserMobileLogin not implemented")
}
func (UnimplementedUserServer) PassengerUserMobileRegister(context.Context, *UserRegisterRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassengerUserMobileRegister not implemented")
}
func (UnimplementedUserServer) PassengerUserPasswordLogin(context.Context, *UserPasswordLoginRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassengerUserPasswordLogin not implemented")
}
func (UnimplementedUserServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServer) UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
}
func (UnimplementedUserServer) SendVerifyCode(context.Context, *SendVerifyCodeRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerifyCode not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_PassengerUserMobileLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).PassengerUserMobileLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_PassengerUserMobileLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).PassengerUserMobileLogin(ctx, req.(*UserLoginRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_PassengerUserMobileRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).PassengerUserMobileRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_PassengerUserMobileRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).PassengerUserMobileRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_PassengerUserPasswordLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPasswordLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).PassengerUserPasswordLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_PassengerUserPasswordLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).PassengerUserPasswordLogin(ctx, req.(*UserPasswordLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SendVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SendVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SendVerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SendVerifyCode(ctx, req.(*SendVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PassengerUserMobileLogin",
			Handler:    _User_PassengerUserMobileLogin_Handler,
		},
		{
			MethodName: "PassengerUserMobileRegister",
			Handler:    _User_PassengerUserMobileRegister_Handler,
		},
		{
			MethodName: "PassengerUserPasswordLogin",
			Handler:    _User_PassengerUserPasswordLogin_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _User_UpdateUserInfo_Handler,
		},
		{
			MethodName: "SendVerifyCode",
			Handler:    _User_SendVerifyCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/user.proto",
}
