// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.11
// source: api/live/live.proto

package live

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLiveCreateLiveRoom = "/api.live.Live/CreateLiveRoom"
const OperationLiveGetLiveRoom = "/api.live.Live/GetLiveRoom"
const OperationLiveGetLiveRoomList = "/api.live.Live/GetLiveRoomList"
const OperationLiveGetViewerList = "/api.live.Live/GetViewerList"
const OperationLiveJoinLiveRoom = "/api.live.Live/JoinLiveRoom"
const OperationLiveLeaveLiveRoom = "/api.live.Live/LeaveLiveRoom"
const OperationLiveStartLive = "/api.live.Live/StartLive"
const OperationLiveStopLive = "/api.live.Live/StopLive"
const OperationLiveUpdateLiveRoom = "/api.live.Live/UpdateLiveRoom"

type LiveHTTPServer interface {
	// CreateLiveRoom =======================直播间管理==========================
	// 创建直播间
	CreateLiveRoom(context.Context, *CreateLiveRoomRequest) (*PleaseReturn, error)
	// GetLiveRoom 获取直播间信息
	GetLiveRoom(context.Context, *GetLiveRoomRequest) (*PleaseReturn, error)
	// GetLiveRoomList 获取直播间列表
	GetLiveRoomList(context.Context, *GetLiveRoomListRequest) (*PleaseReturn, error)
	// GetViewerList 获取观众列表
	GetViewerList(context.Context, *GetViewerListRequest) (*PleaseReturn, error)
	// JoinLiveRoom =======================观众管理==========================
	// 进入直播间
	JoinLiveRoom(context.Context, *JoinLiveRoomRequest) (*PleaseReturn, error)
	// LeaveLiveRoom 退出直播间
	LeaveLiveRoom(context.Context, *LeaveLiveRoomRequest) (*PleaseReturn, error)
	// StartLive 开始直播
	StartLive(context.Context, *StartLiveRequest) (*PleaseReturn, error)
	// StopLive 结束直播
	StopLive(context.Context, *StopLiveRequest) (*PleaseReturn, error)
	// UpdateLiveRoom 更新直播间信息
	UpdateLiveRoom(context.Context, *UpdateLiveRoomRequest) (*PleaseReturn, error)
}

func RegisterLiveHTTPServer(s *http.Server, srv LiveHTTPServer) {
	r := s.Route("/")
	r.POST("/live/room/create", _Live_CreateLiveRoom0_HTTP_Handler(srv))
	r.POST("/live/room/{room_id}/start", _Live_StartLive0_HTTP_Handler(srv))
	r.POST("/live/room/{room_id}/stop", _Live_StopLive0_HTTP_Handler(srv))
	r.GET("/live/room/{room_id}", _Live_GetLiveRoom0_HTTP_Handler(srv))
	r.GET("/live/rooms", _Live_GetLiveRoomList0_HTTP_Handler(srv))
	r.POST("/live/room/{room_id}", _Live_UpdateLiveRoom0_HTTP_Handler(srv))
	r.POST("/live/room/{room_id}/join", _Live_JoinLiveRoom0_HTTP_Handler(srv))
	r.POST("/live/room/{room_id}/leave", _Live_LeaveLiveRoom0_HTTP_Handler(srv))
	r.GET("/live/room/{room_id}/viewers", _Live_GetViewerList0_HTTP_Handler(srv))
}

func _Live_CreateLiveRoom0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLiveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveCreateLiveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLiveRoom(ctx, req.(*CreateLiveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_StartLive0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveStartLive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLive(ctx, req.(*StartLiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_StopLive0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopLiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveStopLive)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopLive(ctx, req.(*StopLiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_GetLiveRoom0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLiveRoomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveGetLiveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLiveRoom(ctx, req.(*GetLiveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_GetLiveRoomList0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLiveRoomListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveGetLiveRoomList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLiveRoomList(ctx, req.(*GetLiveRoomListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_UpdateLiveRoom0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLiveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveUpdateLiveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLiveRoom(ctx, req.(*UpdateLiveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_JoinLiveRoom0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinLiveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveJoinLiveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JoinLiveRoom(ctx, req.(*JoinLiveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_LeaveLiveRoom0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LeaveLiveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveLeaveLiveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LeaveLiveRoom(ctx, req.(*LeaveLiveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

func _Live_GetViewerList0_HTTP_Handler(srv LiveHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetViewerListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiveGetViewerList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetViewerList(ctx, req.(*GetViewerListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PleaseReturn)
		return ctx.Result(200, reply)
	}
}

type LiveHTTPClient interface {
	// CreateLiveRoom =======================直播间管理==========================
	// 创建直播间
	CreateLiveRoom(ctx context.Context, req *CreateLiveRoomRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// GetLiveRoom 获取直播间信息
	GetLiveRoom(ctx context.Context, req *GetLiveRoomRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// GetLiveRoomList 获取直播间列表
	GetLiveRoomList(ctx context.Context, req *GetLiveRoomListRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// GetViewerList 获取观众列表
	GetViewerList(ctx context.Context, req *GetViewerListRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// JoinLiveRoom =======================观众管理==========================
	// 进入直播间
	JoinLiveRoom(ctx context.Context, req *JoinLiveRoomRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// LeaveLiveRoom 退出直播间
	LeaveLiveRoom(ctx context.Context, req *LeaveLiveRoomRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// StartLive 开始直播
	StartLive(ctx context.Context, req *StartLiveRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// StopLive 结束直播
	StopLive(ctx context.Context, req *StopLiveRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
	// UpdateLiveRoom 更新直播间信息
	UpdateLiveRoom(ctx context.Context, req *UpdateLiveRoomRequest, opts ...http.CallOption) (rsp *PleaseReturn, err error)
}

type LiveHTTPClientImpl struct {
	cc *http.Client
}

func NewLiveHTTPClient(client *http.Client) LiveHTTPClient {
	return &LiveHTTPClientImpl{client}
}

// CreateLiveRoom =======================直播间管理==========================
// 创建直播间
func (c *LiveHTTPClientImpl) CreateLiveRoom(ctx context.Context, in *CreateLiveRoomRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveCreateLiveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLiveRoom 获取直播间信息
func (c *LiveHTTPClientImpl) GetLiveRoom(ctx context.Context, in *GetLiveRoomRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiveGetLiveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLiveRoomList 获取直播间列表
func (c *LiveHTTPClientImpl) GetLiveRoomList(ctx context.Context, in *GetLiveRoomListRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/rooms"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiveGetLiveRoomList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetViewerList 获取观众列表
func (c *LiveHTTPClientImpl) GetViewerList(ctx context.Context, in *GetViewerListRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}/viewers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiveGetViewerList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// JoinLiveRoom =======================观众管理==========================
// 进入直播间
func (c *LiveHTTPClientImpl) JoinLiveRoom(ctx context.Context, in *JoinLiveRoomRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}/join"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveJoinLiveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LeaveLiveRoom 退出直播间
func (c *LiveHTTPClientImpl) LeaveLiveRoom(ctx context.Context, in *LeaveLiveRoomRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}/leave"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveLeaveLiveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartLive 开始直播
func (c *LiveHTTPClientImpl) StartLive(ctx context.Context, in *StartLiveRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveStartLive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StopLive 结束直播
func (c *LiveHTTPClientImpl) StopLive(ctx context.Context, in *StopLiveRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveStopLive))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLiveRoom 更新直播间信息
func (c *LiveHTTPClientImpl) UpdateLiveRoom(ctx context.Context, in *UpdateLiveRoomRequest, opts ...http.CallOption) (*PleaseReturn, error) {
	var out PleaseReturn
	pattern := "/live/room/{room_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiveUpdateLiveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
