// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: api/live/live.proto

package live

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 直播间状态
type LiveRoomStatus int32

const (
	LiveRoomStatus_ROOM_CREATED LiveRoomStatus = 0 // 已创建
	LiveRoomStatus_ROOM_LIVE    LiveRoomStatus = 1 // 直播中
	LiveRoomStatus_ROOM_PAUSED  LiveRoomStatus = 2 // 暂停
	LiveRoomStatus_ROOM_ENDED   LiveRoomStatus = 3 // 已结束
	LiveRoomStatus_ROOM_BANNED  LiveRoomStatus = 4 // 被封禁
)

// Enum value maps for LiveRoomStatus.
var (
	LiveRoomStatus_name = map[int32]string{
		0: "ROOM_CREATED",
		1: "ROOM_LIVE",
		2: "ROOM_PAUSED",
		3: "ROOM_ENDED",
		4: "ROOM_BANNED",
	}
	LiveRoomStatus_value = map[string]int32{
		"ROOM_CREATED": 0,
		"ROOM_LIVE":    1,
		"ROOM_PAUSED":  2,
		"ROOM_ENDED":   3,
		"ROOM_BANNED":  4,
	}
)

func (x LiveRoomStatus) Enum() *LiveRoomStatus {
	p := new(LiveRoomStatus)
	*p = x
	return p
}

func (x LiveRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_live_live_proto_enumTypes[0].Descriptor()
}

func (LiveRoomStatus) Type() protoreflect.EnumType {
	return &file_api_live_live_proto_enumTypes[0]
}

func (x LiveRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveRoomStatus.Descriptor instead.
func (LiveRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{0}
}

// 直播类型
type LiveType int32

const (
	LiveType_NORMAL    LiveType = 0 // 普通直播
	LiveType_GAME      LiveType = 1 // 游戏直播
	LiveType_MUSIC     LiveType = 2 // 音乐直播
	LiveType_CHAT      LiveType = 3 // 聊天直播
	LiveType_EDUCATION LiveType = 4 // 教育直播
)

// Enum value maps for LiveType.
var (
	LiveType_name = map[int32]string{
		0: "NORMAL",
		1: "GAME",
		2: "MUSIC",
		3: "CHAT",
		4: "EDUCATION",
	}
	LiveType_value = map[string]int32{
		"NORMAL":    0,
		"GAME":      1,
		"MUSIC":     2,
		"CHAT":      3,
		"EDUCATION": 4,
	}
)

func (x LiveType) Enum() *LiveType {
	p := new(LiveType)
	*p = x
	return p
}

func (x LiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_live_live_proto_enumTypes[1].Descriptor()
}

func (LiveType) Type() protoreflect.EnumType {
	return &file_api_live_live_proto_enumTypes[1]
}

func (x LiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveType.Descriptor instead.
func (LiveType) EnumDescriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{1}
}

// 礼物类型
type GiftType int32

const (
	GiftType_FLOWER GiftType = 0 // 鲜花
	GiftType_HEART  GiftType = 1 // 爱心
	GiftType_ROCKET GiftType = 2 // 火箭
	GiftType_CROWN  GiftType = 3 // 皇冠
)

// Enum value maps for GiftType.
var (
	GiftType_name = map[int32]string{
		0: "FLOWER",
		1: "HEART",
		2: "ROCKET",
		3: "CROWN",
	}
	GiftType_value = map[string]int32{
		"FLOWER": 0,
		"HEART":  1,
		"ROCKET": 2,
		"CROWN":  3,
	}
)

func (x GiftType) Enum() *GiftType {
	p := new(GiftType)
	*p = x
	return p
}

func (x GiftType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GiftType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_live_live_proto_enumTypes[2].Descriptor()
}

func (GiftType) Type() protoreflect.EnumType {
	return &file_api_live_live_proto_enumTypes[2]
}

func (x GiftType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GiftType.Descriptor instead.
func (GiftType) EnumDescriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{2}
}

type CreateLiveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	LiveType      LiveType               `protobuf:"varint,5,opt,name=live_type,json=liveType,proto3,enum=api.live.LiveType" json:"live_type,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiveRoomRequest) Reset() {
	*x = CreateLiveRoomRequest{}
	mi := &file_api_live_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveRoomRequest) ProtoMessage() {}

func (x *CreateLiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateLiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLiveRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLiveRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLiveRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLiveRoomRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateLiveRoomRequest) GetLiveType() LiveType {
	if x != nil {
		return x.LiveType
	}
	return LiveType_NORMAL
}

func (x *CreateLiveRoomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateLiveRoomRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateLiveRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type StartLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLiveRequest) Reset() {
	*x = StartLiveRequest{}
	mi := &file_api_live_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveRequest) ProtoMessage() {}

func (x *StartLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveRequest.ProtoReflect.Descriptor instead.
func (*StartLiveRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{1}
}

func (x *StartLiveRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StartLiveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type StopLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLiveRequest) Reset() {
	*x = StopLiveRequest{}
	mi := &file_api_live_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLiveRequest) ProtoMessage() {}

func (x *StopLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLiveRequest.ProtoReflect.Descriptor instead.
func (*StopLiveRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{2}
}

func (x *StopLiveRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StopLiveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLiveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRoomRequest) Reset() {
	*x = GetLiveRoomRequest{}
	mi := &file_api_live_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRoomRequest) ProtoMessage() {}

func (x *GetLiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRoomRequest.ProtoReflect.Descriptor instead.
func (*GetLiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{3}
}

func (x *GetLiveRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetLiveRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLiveRoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                                // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                        // 每页数量
	LiveType      LiveType               `protobuf:"varint,3,opt,name=live_type,json=liveType,proto3,enum=api.live.LiveType" json:"live_type,omitempty"` // 直播类型筛选
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`                                           // 搜索关键词
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                               // 排序方式: popularity, create_time, viewer_count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRoomListRequest) Reset() {
	*x = GetLiveRoomListRequest{}
	mi := &file_api_live_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRoomListRequest) ProtoMessage() {}

func (x *GetLiveRoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRoomListRequest.ProtoReflect.Descriptor instead.
func (*GetLiveRoomListRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{4}
}

func (x *GetLiveRoomListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLiveRoomListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLiveRoomListRequest) GetLiveType() LiveType {
	if x != nil {
		return x.LiveType
	}
	return LiveType_NORMAL
}

func (x *GetLiveRoomListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetLiveRoomListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type UpdateLiveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`      // 直播间ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 主播用户ID
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                       // 直播间标题
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`           // 直播间描述
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 封面图片URL
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`                         // 标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLiveRoomRequest) Reset() {
	*x = UpdateLiveRoomRequest{}
	mi := &file_api_live_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveRoomRequest) ProtoMessage() {}

func (x *UpdateLiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateLiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLiveRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *UpdateLiveRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateLiveRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLiveRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLiveRoomRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateLiveRoomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type JoinLiveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLiveRoomRequest) Reset() {
	*x = JoinLiveRoomRequest{}
	mi := &file_api_live_live_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLiveRoomRequest) ProtoMessage() {}

func (x *JoinLiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLiveRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinLiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{6}
}

func (x *JoinLiveRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinLiveRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinLiveRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LeaveLiveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLiveRoomRequest) Reset() {
	*x = LeaveLiveRoomRequest{}
	mi := &file_api_live_live_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLiveRoomRequest) ProtoMessage() {}

func (x *LeaveLiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLiveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveLiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveLiveRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LeaveLiveRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetViewerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerListRequest) Reset() {
	*x = GetViewerListRequest{}
	mi := &file_api_live_live_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerListRequest) ProtoMessage() {}

func (x *GetViewerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerListRequest.ProtoReflect.Descriptor instead.
func (*GetViewerListRequest) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{8}
}

func (x *GetViewerListRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetViewerListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetViewerListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PleaseReturn 参数返回三要素
type PleaseReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleaseReturn) Reset() {
	*x = PleaseReturn{}
	mi := &file_api_live_live_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleaseReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleaseReturn) ProtoMessage() {}

func (x *PleaseReturn) ProtoReflect() protoreflect.Message {
	mi := &file_api_live_live_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleaseReturn.ProtoReflect.Descriptor instead.
func (*PleaseReturn) Descriptor() ([]byte, []int) {
	return file_api_live_live_proto_rawDescGZIP(), []int{9}
}

func (x *PleaseReturn) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PleaseReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PleaseReturn) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_live_live_proto protoreflect.FileDescriptor

const file_api_live_live_proto_rawDesc = "" +
	"\n" +
	"\x13api/live/live.proto\x12\bapi.live\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x15CreateLiveRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12/\n" +
	"\tlive_type\x18\x05 \x01(\x0e2\x12.api.live.LiveTypeR\bliveType\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\"D\n" +
	"\x10StartLiveRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"C\n" +
	"\x0fStopLiveRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"F\n" +
	"\x12GetLiveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xad\x01\n" +
	"\x16GetLiveRoomListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12/\n" +
	"\tlive_type\x18\x03 \x01(\x0e2\x12.api.live.LiveTypeR\bliveType\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\"\xb2\x01\n" +
	"\x15UpdateLiveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"c\n" +
	"\x13JoinLiveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"H\n" +
	"\x14LeaveLiveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"`\n" +
	"\x14GetViewerListRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"a\n" +
	"\fPleaseReturn\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data*c\n" +
	"\x0eLiveRoomStatus\x12\x10\n" +
	"\fROOM_CREATED\x10\x00\x12\r\n" +
	"\tROOM_LIVE\x10\x01\x12\x0f\n" +
	"\vROOM_PAUSED\x10\x02\x12\x0e\n" +
	"\n" +
	"ROOM_ENDED\x10\x03\x12\x0f\n" +
	"\vROOM_BANNED\x10\x04*D\n" +
	"\bLiveType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\b\n" +
	"\x04GAME\x10\x01\x12\t\n" +
	"\x05MUSIC\x10\x02\x12\b\n" +
	"\x04CHAT\x10\x03\x12\r\n" +
	"\tEDUCATION\x10\x04*8\n" +
	"\bGiftType\x12\n" +
	"\n" +
	"\x06FLOWER\x10\x00\x12\t\n" +
	"\x05HEART\x10\x01\x12\n" +
	"\n" +
	"\x06ROCKET\x10\x02\x12\t\n" +
	"\x05CROWN\x10\x032\xb9\a\n" +
	"\x04Live\x12g\n" +
	"\x0eCreateLiveRoom\x12\x1f.api.live.CreateLiveRoomRequest\x1a\x16.api.live.PleaseReturn\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/live/room/create\x12f\n" +
	"\tStartLive\x12\x1a.api.live.StartLiveRequest\x1a\x16.api.live.PleaseReturn\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/live/room/{room_id}/start\x12c\n" +
	"\bStopLive\x12\x19.api.live.StopLiveRequest\x1a\x16.api.live.PleaseReturn\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/live/room/{room_id}/stop\x12a\n" +
	"\vGetLiveRoom\x12\x1c.api.live.GetLiveRoomRequest\x1a\x16.api.live.PleaseReturn\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/live/room/{room_id}\x12`\n" +
	"\x0fGetLiveRoomList\x12 .api.live.GetLiveRoomListRequest\x1a\x16.api.live.PleaseReturn\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/live/rooms\x12j\n" +
	"\x0eUpdateLiveRoom\x12\x1f.api.live.UpdateLiveRoomRequest\x1a\x16.api.live.PleaseReturn\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/live/room/{room_id}\x12k\n" +
	"\fJoinLiveRoom\x12\x1d.api.live.JoinLiveRoomRequest\x1a\x16.api.live.PleaseReturn\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/live/room/{room_id}/join\x12n\n" +
	"\rLeaveLiveRoom\x12\x1e.api.live.LeaveLiveRoomRequest\x1a\x16.api.live.PleaseReturn\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/live/room/{room_id}/leave\x12m\n" +
	"\rGetViewerList\x12\x1e.api.live.GetViewerListRequest\x1a\x16.api.live.PleaseReturn\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/live/room/{room_id}/viewersB'\n" +
	"\bapi.liveP\x01Z\x19kratosItems/api/live;liveb\x06proto3"

var (
	file_api_live_live_proto_rawDescOnce sync.Once
	file_api_live_live_proto_rawDescData []byte
)

func file_api_live_live_proto_rawDescGZIP() []byte {
	file_api_live_live_proto_rawDescOnce.Do(func() {
		file_api_live_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_live_live_proto_rawDesc), len(file_api_live_live_proto_rawDesc)))
	})
	return file_api_live_live_proto_rawDescData
}

var file_api_live_live_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_live_live_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_live_live_proto_goTypes = []any{
	(LiveRoomStatus)(0),            // 0: api.live.LiveRoomStatus
	(LiveType)(0),                  // 1: api.live.LiveType
	(GiftType)(0),                  // 2: api.live.GiftType
	(*CreateLiveRoomRequest)(nil),  // 3: api.live.CreateLiveRoomRequest
	(*StartLiveRequest)(nil),       // 4: api.live.StartLiveRequest
	(*StopLiveRequest)(nil),        // 5: api.live.StopLiveRequest
	(*GetLiveRoomRequest)(nil),     // 6: api.live.GetLiveRoomRequest
	(*GetLiveRoomListRequest)(nil), // 7: api.live.GetLiveRoomListRequest
	(*UpdateLiveRoomRequest)(nil),  // 8: api.live.UpdateLiveRoomRequest
	(*JoinLiveRoomRequest)(nil),    // 9: api.live.JoinLiveRoomRequest
	(*LeaveLiveRoomRequest)(nil),   // 10: api.live.LeaveLiveRoomRequest
	(*GetViewerListRequest)(nil),   // 11: api.live.GetViewerListRequest
	(*PleaseReturn)(nil),           // 12: api.live.PleaseReturn
	(*structpb.Struct)(nil),        // 13: google.protobuf.Struct
}
var file_api_live_live_proto_depIdxs = []int32{
	1,  // 0: api.live.CreateLiveRoomRequest.live_type:type_name -> api.live.LiveType
	1,  // 1: api.live.GetLiveRoomListRequest.live_type:type_name -> api.live.LiveType
	13, // 2: api.live.PleaseReturn.data:type_name -> google.protobuf.Struct
	3,  // 3: api.live.Live.CreateLiveRoom:input_type -> api.live.CreateLiveRoomRequest
	4,  // 4: api.live.Live.StartLive:input_type -> api.live.StartLiveRequest
	5,  // 5: api.live.Live.StopLive:input_type -> api.live.StopLiveRequest
	6,  // 6: api.live.Live.GetLiveRoom:input_type -> api.live.GetLiveRoomRequest
	7,  // 7: api.live.Live.GetLiveRoomList:input_type -> api.live.GetLiveRoomListRequest
	8,  // 8: api.live.Live.UpdateLiveRoom:input_type -> api.live.UpdateLiveRoomRequest
	9,  // 9: api.live.Live.JoinLiveRoom:input_type -> api.live.JoinLiveRoomRequest
	10, // 10: api.live.Live.LeaveLiveRoom:input_type -> api.live.LeaveLiveRoomRequest
	11, // 11: api.live.Live.GetViewerList:input_type -> api.live.GetViewerListRequest
	12, // 12: api.live.Live.CreateLiveRoom:output_type -> api.live.PleaseReturn
	12, // 13: api.live.Live.StartLive:output_type -> api.live.PleaseReturn
	12, // 14: api.live.Live.StopLive:output_type -> api.live.PleaseReturn
	12, // 15: api.live.Live.GetLiveRoom:output_type -> api.live.PleaseReturn
	12, // 16: api.live.Live.GetLiveRoomList:output_type -> api.live.PleaseReturn
	12, // 17: api.live.Live.UpdateLiveRoom:output_type -> api.live.PleaseReturn
	12, // 18: api.live.Live.JoinLiveRoom:output_type -> api.live.PleaseReturn
	12, // 19: api.live.Live.LeaveLiveRoom:output_type -> api.live.PleaseReturn
	12, // 20: api.live.Live.GetViewerList:output_type -> api.live.PleaseReturn
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_live_live_proto_init() }
func file_api_live_live_proto_init() {
	if File_api_live_live_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_live_live_proto_rawDesc), len(file_api_live_live_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_live_live_proto_goTypes,
		DependencyIndexes: file_api_live_live_proto_depIdxs,
		EnumInfos:         file_api_live_live_proto_enumTypes,
		MessageInfos:      file_api_live_live_proto_msgTypes,
	}.Build()
	File_api_live_live_proto = out.File
	file_api_live_live_proto_goTypes = nil
	file_api_live_live_proto_depIdxs = nil
}
