// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: api/live/live.proto

package live

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Live_CreateLiveRoom_FullMethodName  = "/api.live.Live/CreateLiveRoom"
	Live_StartLive_FullMethodName       = "/api.live.Live/StartLive"
	Live_StopLive_FullMethodName        = "/api.live.Live/StopLive"
	Live_GetLiveRoom_FullMethodName     = "/api.live.Live/GetLiveRoom"
	Live_GetLiveRoomList_FullMethodName = "/api.live.Live/GetLiveRoomList"
	Live_UpdateLiveRoom_FullMethodName  = "/api.live.Live/UpdateLiveRoom"
	Live_JoinLiveRoom_FullMethodName    = "/api.live.Live/JoinLiveRoom"
	Live_LeaveLiveRoom_FullMethodName   = "/api.live.Live/LeaveLiveRoom"
	Live_GetViewerList_FullMethodName   = "/api.live.Live/GetViewerList"
)

// LiveClient is the client API for Live service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveClient interface {
	// =======================直播间管理==========================
	// 创建直播间
	CreateLiveRoom(ctx context.Context, in *CreateLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 开始直播
	StartLive(ctx context.Context, in *StartLiveRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 结束直播
	StopLive(ctx context.Context, in *StopLiveRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 获取直播间信息
	GetLiveRoom(ctx context.Context, in *GetLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 获取直播间列表
	GetLiveRoomList(ctx context.Context, in *GetLiveRoomListRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 更新直播间信息
	UpdateLiveRoom(ctx context.Context, in *UpdateLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// =======================观众管理==========================
	// 进入直播间
	JoinLiveRoom(ctx context.Context, in *JoinLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 退出直播间
	LeaveLiveRoom(ctx context.Context, in *LeaveLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
	// 获取观众列表
	GetViewerList(ctx context.Context, in *GetViewerListRequest, opts ...grpc.CallOption) (*PleaseReturn, error)
}

type liveClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveClient(cc grpc.ClientConnInterface) LiveClient {
	return &liveClient{cc}
}

func (c *liveClient) CreateLiveRoom(ctx context.Context, in *CreateLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_CreateLiveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) StartLive(ctx context.Context, in *StartLiveRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_StartLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) StopLive(ctx context.Context, in *StopLiveRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_StopLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) GetLiveRoom(ctx context.Context, in *GetLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_GetLiveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) GetLiveRoomList(ctx context.Context, in *GetLiveRoomListRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_GetLiveRoomList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) UpdateLiveRoom(ctx context.Context, in *UpdateLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_UpdateLiveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) JoinLiveRoom(ctx context.Context, in *JoinLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_JoinLiveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) LeaveLiveRoom(ctx context.Context, in *LeaveLiveRoomRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_LeaveLiveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveClient) GetViewerList(ctx context.Context, in *GetViewerListRequest, opts ...grpc.CallOption) (*PleaseReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PleaseReturn)
	err := c.cc.Invoke(ctx, Live_GetViewerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveServer is the server API for Live service.
// All implementations must embed UnimplementedLiveServer
// for forward compatibility.
type LiveServer interface {
	// =======================直播间管理==========================
	// 创建直播间
	CreateLiveRoom(context.Context, *CreateLiveRoomRequest) (*PleaseReturn, error)
	// 开始直播
	StartLive(context.Context, *StartLiveRequest) (*PleaseReturn, error)
	// 结束直播
	StopLive(context.Context, *StopLiveRequest) (*PleaseReturn, error)
	// 获取直播间信息
	GetLiveRoom(context.Context, *GetLiveRoomRequest) (*PleaseReturn, error)
	// 获取直播间列表
	GetLiveRoomList(context.Context, *GetLiveRoomListRequest) (*PleaseReturn, error)
	// 更新直播间信息
	UpdateLiveRoom(context.Context, *UpdateLiveRoomRequest) (*PleaseReturn, error)
	// =======================观众管理==========================
	// 进入直播间
	JoinLiveRoom(context.Context, *JoinLiveRoomRequest) (*PleaseReturn, error)
	// 退出直播间
	LeaveLiveRoom(context.Context, *LeaveLiveRoomRequest) (*PleaseReturn, error)
	// 获取观众列表
	GetViewerList(context.Context, *GetViewerListRequest) (*PleaseReturn, error)
	mustEmbedUnimplementedLiveServer()
}

// UnimplementedLiveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveServer struct{}

func (UnimplementedLiveServer) CreateLiveRoom(context.Context, *CreateLiveRoomRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLiveRoom not implemented")
}
func (UnimplementedLiveServer) StartLive(context.Context, *StartLiveRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLive not implemented")
}
func (UnimplementedLiveServer) StopLive(context.Context, *StopLiveRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLive not implemented")
}
func (UnimplementedLiveServer) GetLiveRoom(context.Context, *GetLiveRoomRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveRoom not implemented")
}
func (UnimplementedLiveServer) GetLiveRoomList(context.Context, *GetLiveRoomListRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveRoomList not implemented")
}
func (UnimplementedLiveServer) UpdateLiveRoom(context.Context, *UpdateLiveRoomRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLiveRoom not implemented")
}
func (UnimplementedLiveServer) JoinLiveRoom(context.Context, *JoinLiveRoomRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinLiveRoom not implemented")
}
func (UnimplementedLiveServer) LeaveLiveRoom(context.Context, *LeaveLiveRoomRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveLiveRoom not implemented")
}
func (UnimplementedLiveServer) GetViewerList(context.Context, *GetViewerListRequest) (*PleaseReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewerList not implemented")
}
func (UnimplementedLiveServer) mustEmbedUnimplementedLiveServer() {}
func (UnimplementedLiveServer) testEmbeddedByValue()              {}

// UnsafeLiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveServer will
// result in compilation errors.
type UnsafeLiveServer interface {
	mustEmbedUnimplementedLiveServer()
}

func RegisterLiveServer(s grpc.ServiceRegistrar, srv LiveServer) {
	// If the following call pancis, it indicates UnimplementedLiveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Live_ServiceDesc, srv)
}

func _Live_CreateLiveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLiveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).CreateLiveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_CreateLiveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).CreateLiveRoom(ctx, req.(*CreateLiveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_StartLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).StartLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_StartLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).StartLive(ctx, req.(*StartLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_StopLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).StopLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_StopLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).StopLive(ctx, req.(*StopLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_GetLiveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).GetLiveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_GetLiveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).GetLiveRoom(ctx, req.(*GetLiveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_GetLiveRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveRoomListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).GetLiveRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_GetLiveRoomList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).GetLiveRoomList(ctx, req.(*GetLiveRoomListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_UpdateLiveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLiveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).UpdateLiveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_UpdateLiveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).UpdateLiveRoom(ctx, req.(*UpdateLiveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_JoinLiveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinLiveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).JoinLiveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_JoinLiveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).JoinLiveRoom(ctx, req.(*JoinLiveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_LeaveLiveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveLiveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).LeaveLiveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_LeaveLiveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).LeaveLiveRoom(ctx, req.(*LeaveLiveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Live_GetViewerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveServer).GetViewerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Live_GetViewerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveServer).GetViewerList(ctx, req.(*GetViewerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Live_ServiceDesc is the grpc.ServiceDesc for Live service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Live_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.live.Live",
	HandlerType: (*LiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLiveRoom",
			Handler:    _Live_CreateLiveRoom_Handler,
		},
		{
			MethodName: "StartLive",
			Handler:    _Live_StartLive_Handler,
		},
		{
			MethodName: "StopLive",
			Handler:    _Live_StopLive_Handler,
		},
		{
			MethodName: "GetLiveRoom",
			Handler:    _Live_GetLiveRoom_Handler,
		},
		{
			MethodName: "GetLiveRoomList",
			Handler:    _Live_GetLiveRoomList_Handler,
		},
		{
			MethodName: "UpdateLiveRoom",
			Handler:    _Live_UpdateLiveRoom_Handler,
		},
		{
			MethodName: "JoinLiveRoom",
			Handler:    _Live_JoinLiveRoom_Handler,
		},
		{
			MethodName: "LeaveLiveRoom",
			Handler:    _Live_LeaveLiveRoom_Handler,
		},
		{
			MethodName: "GetViewerList",
			Handler:    _Live_GetViewerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/live/live.proto",
}
